language: node_js
node_js:
 - 'node'

before_install:
  - "npm install elm@0.18"

script: elm-make --yes src/Main.elm

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
